Make TotalThroughputSampler a valid sampler.
honeycombio/refinery pull request #191
Opened 2020-11-11 15:25 UTC by magnusstahre

2020-11-12 18:23 UTC, martin308 requested changes
It's probably worth adding a bunch of extra tests to cover these points we missed! 

Could we add:

- a sample config to rules.toml similar to the others
- a test in config_test for this sampler config

2020-11-30 17:18 UTC, magnusstahre commented
@martin308 updated the PR per the requests, please take a look!

2020-11-30 22:24 UTC, asdvalenzuela approved these changes

2020-11-30 22:30 UTC, martin308 approved these changes
✨

2020-11-30 22:32 UTC, merged