Add support for OTLP over HTTP/protobuf
honeycombio/refinery pull request #279
Opened 2021-07-01 20:35 UTC by MikeGoldsmith

Adds support for ingesting OTLP requests over HTTP with protobuf data. Changs in this PR:

- Move the existing gRPC export handler and helpers to to otlp_trace.go and tests into otlp_trace_test.go
- Add HTTP handler `postOTLP` that retrieves honeycomb headers, decodes the request body into a OTLP ExportTraceRequest and hands to internal function to process request
- Update OTLP grpc Export handler to retrieve honeycomb headers from metadata and hand request to new internal function to process
- Adds tests to verify rejection behaviour for non-protobuf based requests to postOTLP and test to pass request to postOTLP handler endpoint

2021-07-06 14:05 UTC, MikeGoldsmith commented
Most recent commits was to add support for gzip/zstd encoding as part of the parsing process.

2021-07-08 21:02 UTC, vreynolds requested changes
Route requires an extra `/1/` path

2021-07-12 12:44 UTC, MikeGoldsmith commented on route/route.go
> +	authedMuxxer.HandleFunc("/v1/traces", r.postOTLP).Name("otlp")
Hmm, I thought I tested this but must have been confused with testing Hound. Thanks for catching @vreynolds 👍🏻

2021-07-12 16:57 UTC, vreynolds commented on route/route.go
> +	authedMuxxer.HandleFunc("/v1/traces", r.postOTLP).Name("otlp")
Do you actually see OTLP data posted to Honeycomb? I'm seeing the same logs, but as I read them, it's telling us `proxying request for /v1/traces` which got [here](https://github.com/honeycombio/refinery/blob/8c28b313627e3f0ec0635a3fc827273d4d7f3b52/route/proxy.go#L14), so I don't think the router actually used the OTLP handler, right?

In the client, I'm seeing `OpenTelemetry error: Unable to export 10 spans`

2021-07-12 17:00 UTC, vreynolds commented on route/route.go
> +	authedMuxxer.HandleFunc("/v1/traces", r.postOTLP).Name("otlp")
If I change the client OTLP endpoint to `localhost/1` Refinery logs `handled otlp request tSqX0iR9 [::1]:63470 POST /1/v1/traces 0.794175 200` and spans come through

2021-07-13 14:26 UTC, MikeGoldsmith commented on route/route.go
> +	authedMuxxer.HandleFunc("/v1/traces", r.postOTLP).Name("otlp")
Yeah, I got data through to my local Shepherd that I can query on in the UI.

![otlp-http-refinery](https://user-images.githubusercontent.com/3481731/125469400-cb376d68-be23-46a9-9ed2-04fecbc53b8a.gif)

2021-07-13 14:35 UTC, MikeGoldsmith commented on route/route.go
> +	authedMuxxer.HandleFunc("/v1/traces", r.postOTLP).Name("otlp")
I was using the [ruby-otlp](https://github.com/honeycombio/examples/tree/main/ruby-otlp) example and set the following env vars:
```
export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:18080
export OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=a012e0a06d90af50a61a5ce4e9e19737,x-honeycomb-dataset=ruby-otlp
export SERVICE_NAME=ruby-otlp
``

2021-07-13 16:20 UTC, vreynolds commented on route/route.go
> +	authedMuxxer.HandleFunc("/v1/traces", r.postOTLP).Name("otlp")
For posterity: we paired on zoom, and it looks like the crux is using local shepherd vs dogfood. It still looks like requests aren't handled properly by refinery, but when paired with local shepherd, proxied (unhandled) requests still get processed, whereas when paired with dogfood, they get rejected.

2021-07-13 21:28 UTC, MikeGoldsmith commented on route/route.go
> +	authedMuxxer.HandleFunc("/v1/traces", r.postOTLP).Name("otlp")
I've added a new `otlpmuxxer` that handles OTLP requests with the `/v1/` prefix in [49732c1](https://github.com/honeycombio/refinery/pull/279/commits/49732c13447b5308f3835019f8a9ad9c6d75e2e6)

2021-07-13 21:51 UTC, vreynolds approved these changes
![she-ready](https://user-images.githubusercontent.com/6738917/125530032-2244c7d5-51e6-4297-a2e8-12367d920d0c.gif)

2021-07-14 09:40 UTC, merged