Implement grpc-health-probe
honeycombio/refinery pull request #498
Opened 2022-09-03 14:07 UTC by abatilo

Similar to the `/x/alive` endpoint for the http server, this PR
implements the gRPC handlers for the [gRPC Health Checking
Protocol](https://github.com/grpc/grpc/blob/592bfb9c0040fba382e5dc106e2ebbf0c96465fb/doc/health-checking.md).

I was able to verify that this works by running refinery with the
complete config to set `GRPCListenAddr = "0.0.0.0:9090"`:
```
⇒  go run ./cmd/refinery -c config_complete.toml -r rules_complete.toml
...
```

And then I could run the
[grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe)
binary:
```
⇒  grpc-health-probe -addr=localhost:9090
status: SERVING
```

Closes #414

2022-09-03 14:11 UTC, abatilo commented
Tagging @kentquirk also since that's who had opened the original issue!

2022-09-04 15:38 UTC, kentquirk commented
@abatilo -- Thank you for this! We are really trying not to add new code to things without having a test for it. It verifies the functionality, but also provides a backstop against regressions later as well as documentation of expected behavior. 

Any chance you could write tests to verify this? Ideally they'd operate by an endpoint request, but even a test at the Route level would help.

2022-09-06 09:27 UTC, MikeGoldsmith requested changes
As @kentquirk requested, please can you add a test to verify the new endpoint works as expected 👍🏻

2022-09-06 14:58 UTC, abatilo commented
> @abatilo -- Thank you for this! We are really trying not to add new code to things without having a test for it. It verifies the functionality, but also provides a backstop against regressions later as well as documentation of expected behavior.
> 
> Any chance you could write tests to verify this? Ideally they'd operate by an endpoint request, but even a test at the Route level would help.

Thanks for the feedback, @kentquirk. I noticed that there weren't tests covering endpoints like `/alive` so I wasn't 100% sure what the preference was going to be. I'll think about how I might implement this and get back to you!

2022-09-07 02:46 UTC, abatilo commented
Hi @MikeGoldsmith @kentquirk.

How do we feel about [these tests](https://github.com/honeycombio/refinery/pull/498/files#diff-2e9ae5a252a7f32fe100e1e6c89103596d3c07999b8c010357aa626fe25d9e2fR524-R559)?

I took inspiration from [otlp_trace_test.go](https://github.com/abatilo/refinery/blob/ce4bf6a8df76462369cdd75965220efcd929483c/route/otlp_trace_test.go#L68-L80).

Thanks again for helping me contribute.

2022-09-07 09:46 UTC, MikeGoldsmith commented
Yep, these look great - thanks @abatilo 👍🏻

2022-09-07 09:47 UTC, MikeGoldsmith approved these changes
Thanks for your contribution @abatilo 🎉

2022-09-07 09:48 UTC, merged