allow BatchTimeout to be overriden on the libhoney Transmission
honeycombio/refinery pull request #509
Opened 2022-09-09 20:21 UTC by leviwilson

## Which problem is this PR solving?

We have an issue where our ALB traffic has a `~5m` latency because of the cadence in which the CloudWatch logs are sent. Because the ALB represents our top-level traces, this means that _all_ web traffic is delayed by that same amount.

Decreasing the `TraceTimeout` value assists with this by spreading out the traffic, however this makes our rules a moot point as things we are intentionally trying to downsample do not get downsampled.

What we _really_ need is a manner to control how frequently events are sent upstream to Honeycomb so we can control how frequently we send things. https://github.com/honeycombio/libhoney-go/blob/8af08e456cfe1f786247ffdc755855999add2d76/libhoney.go#L136 indicates that `SendFrequency` can override how often batches are sent.

## Short description of the changes

This PR allows for the `BatchTimeout` to be configured for refinery rather than explicitly using `DefaultBatchTimeout`. I realize `SendFrequency` is what was mentioned above, but refinery calls `NewClient` rather than `Init` and you can see that all `SendFrequency` does is drive `BatchTimeout` on [the `Transmission` anyway](https://github.com/honeycombio/libhoney-go/blob/8af08e456cfe1f786247ffdc755855999add2d76/libhoney.go#L236).

2022-09-12 12:43 UTC, MikeGoldsmith requested changes
Looks great, thanks @leviwilson 🎉 

Only thing missing is adding an example to the [config_config.toml](https://github.com/honeycombio/refinery/blob/main/config_complete.toml#L59) to show it being overriden.

2022-09-12 13:16 UTC, leviwilson commented
> Looks great, thanks @leviwilson 🎉
> 
> Only thing missing is adding an example to the [config_config.toml](https://github.com/honeycombio/refinery/blob/main/config_complete.toml#L59) to show it being overriden.

done

2022-09-12 19:29 UTC, jessitron commented
Thanks @leviwilson !

@MikeGoldsmith fyi someday there's a more interesting problem to solve here, of refinery noticing Honeycomb's rate-limiting errors and adapting.

This change will go a long way toward letting people solve this problem themselves now.

2022-09-14 15:10 UTC, MikeGoldsmith approved these changes
Thanks @leviwilson 🎉

2022-09-14 21:01 UTC, merged