prepare release v1.17.0
honeycombio/refinery pull request #517
Opened 2022-09-16 17:13 UTC by JamieDanielson

## Which problem is this PR solving?

- adds v1.17.0 release

## Short description of the changes

- remove dup entry from previous release in changelog
- add entry for v1.17.0 to changelog

2022-09-16 17:27 UTC, vreynolds approved these changes

2022-09-16 17:32 UTC, emilyashley approved these changes

2022-09-16 18:30 UTC, kentquirk requested changes
Need to put a hold on this while I investigate a crash.

2022-09-17 00:53 UTC, kentquirk approved these changes
I've removed my hold provided that #519 is added as well.

2022-09-19 16:26 UTC, merged